# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 024f4df0008d4702f3346eb0ca41e7d2d879f197e96cf5291cbc7f3e84184f4312f9ddd3f80819e6266298f2b1da0fe291f9db3b506cdc3c1d8a68e1d117a246

test:
  secret_key_base: aa2ffa46ebecd03465174e538cab87d446411fbd17c2b50bc279253ca32310e1cad28884b2c04dd3d2ad0bbad1991a4efd1c2295258c6adac1a1ae94553381d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
